source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UPTBlinkingLabel_Example', :exclusive => true do
  pod "UPTBlinkingLabel", :path => "../"
end

target 'UPTBlinkingLabel_Tests', :exclusive => true do
  pod "UPTBlinkingLabel", :path => "../"

  
end
